repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [file, python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        name: flake8
        args: [--config, .flake8, --max-cognitive-complexity=7]
        additional_dependencies: [flake8-cognitive-complexity]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
