name: unit_test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install pipenv
        run: |
          eco "mock"

      - name: run pytest
        run: |
          eco "mock"

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
