name: unit_test

on:
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  test_in_python3_10:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: install modules
        run: |
          cd python_version/3.10
          pipenv lock
          pipenv sync --dev
          cd ../../

      - name: run pytest
        run: |
          pipenv run pytest -v tests
  test_in_python3_9:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: install modules
        run: |
          pipenv lock
          pipenv sync --dev

      - name: run pytest
        run: |
          pipenv run pytest -v tests/ --cov=src/Pyfrontier --cov-report=xml

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
