name: unit_test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: install modules
        run: |
          cd python_version/3.9
          pipenv sync --dev

      - name: run pytest
        run: |
          cd python_version/3.9
          pipenv shell
          pytest -v tests/ --cov=src/Pyfrontier --cov-report=xml

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
